name: Laravel workflow
run-name: ${{ github.actor }} runs 1

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Testing OS
      run: echo "Running"
    - name: Check Composer Version
      run: composer --version
    - name: Check PHP Version
      run: php -v
    - name: List All Files In Current Directory
      run: ls -al
